CREATE TABLE wc_user_lessons
(
  `id` BIGINT AUTO_INCREMENT COMMENT '自增主键',
  `uid` BIGINT NOT NULL DEFAULT 0 COMMENT '用户uid',
  `songjing` BIGINT NOT NULL DEFAULT 0 COMMENT '用户诵经次数',
  `chanhui` BIGINT NOT NULL DEFAULT 0 COMMENT '用户忏悔次数',
  `nianfo` BIGINT NOT NULL DEFAULT 0 COMMENT '用户念佛次数',
  `date` BIGINT(8) NOT NULL DEFAULT 0 COMMENT '功课日期',
  `create_time` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '记录时间',
  PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户功课';